#!/usr/bin/env python3
"""
OmaPets - Rick and Morty Pixel Asset Generator
Generates crisp, retro pixel-art RGBA PNGs for Pickle Rick, Incubator Vat,
Sci-fi Garage Lab decor, and Emotes.
"""

import os
import subprocess

OUT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "assets", "sprites"))
os.makedirs(OUT_DIR, exist_ok=True)

# Color Palette: Hex to RGBA tuple
PALETTE = {
    '.': (0, 0, 0, 0),          # Transparent
    '#': (18, 38, 16, 255),      # Darkest Pickle Outline / shadow
    'G': (72, 166, 63, 255),     # Pickle Rick Main Green
    'g': (46, 115, 40, 255),     # Pickle Rick Dark Green / Wart
    'L': (116, 204, 102, 255),   # Pickle Rick Highlight Green
    'U': (95, 185, 222, 255),    # Rick Unibrow Cyan/Blue
    'u': (60, 130, 170, 255),    # Rick Unibrow Shadow
    'W': (255, 255, 255, 255),   # Eye Sclera / Teeth White
    'w': (215, 225, 215, 255),   # Eye Shading
    'K': (15, 18, 16, 255),      # Pupil / Mouth Black
    'R': (220, 70, 85, 255),     # Tongue Pink/Red
    'r': (160, 45, 55, 255),     # Deep Mouth Red
    'B': (138, 90, 54, 255),     # Rat Bone / Leather Strap
    'b': (95, 58, 32, 255),      # Dark Leather / Rat Claw
    'S': (180, 190, 195, 255),   # Rat Skull / Metal Screw
    's': (120, 130, 135, 255),   # Dark Metal / Needle
    'Y': (255, 230, 50, 255),    # Stun Star Yellow / Portal Glow
    'y': (220, 180, 20, 255),    # Stun Star Shadow
    'P': (57, 255, 20, 255),     # Neon Portal Green / Incubator Liquid
    'p': (30, 160, 10, 255),     # Darker Incubator Liquid
    'C': (60, 80, 95, 255),      # Sci-fi Metal Console
    'c': (35, 45, 55, 255),      # Dark Sci-fi Metal
    'F': (120, 220, 255, 255),   # Glass reflection / Flask blue
}

def render_grid(grid_str, filename, width=24, height=24):
    lines = [line.strip() for line in grid_str.strip().splitlines() if line.strip()]
    if len(lines) != height:
        raise ValueError(f"Grid height {len(lines)} != {height} for {filename}")
    for i, line in enumerate(lines):
        if len(line) != width:
            raise ValueError(f"Line {i} length {len(line)} != {width} for {filename}")

    header = f"P7\nWIDTH {width}\nHEIGHT {height}\nDEPTH 4\nMAXVAL 255\nTUPLTYPE RGB_ALPHA\nENDHDR\n".encode("ascii")
    pixel_bytes = bytearray()
    for line in lines:
        for char in line:
            rgba = PALETTE.get(char, (0, 0, 0, 0))
            pixel_bytes.extend(rgba)

    pam_data = header + bytes(pixel_bytes)
    target_path = os.path.join(OUT_DIR, filename)
    subprocess.run(["magick", "pam:-", f"PNG32:{target_path}"], input=pam_data, check=True)
    print(f"Generated {filename} ({width}x{height})")


# ==============================================================================
# PICKLE RICK SPRITES (24 x 24)
# ==============================================================================

# 1. Idle Frame A
PICKLE_IDLE_A = """
........................
.........######.........
.......##GGLLGG##.......
......#GgGGLLGGGG#......
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGGUUUUUUGGG#.....
.....#GG#WW##WW#GG#.....
.....#GG#WK##KW#GG#.....
.....#gG#WW##WW#gG#.....
.....#GG#KKKKKK#GG#.....
.....#GG#WWRRWw#GG#.....
.....#GGG#KKKK#GGG#.....
.....#gGGGGGGGGgGG#.....
.....#GGGGGGGGGGGG#.....
......#gGGGGGGgGG#......
......#GGgGGGGGGG#......
......#GGGGgGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
........#GGGGGG#........
.........######.........
.........#b##b#.........
........................
"""

# 2. Idle Frame B (Breathing squeeze & slight eye flicker)
PICKLE_IDLE_B = """
........................
........................
.........######.........
.......##GGLLGG##.......
......#GgGGLLGGGG#......
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGGUUUUUUGGG#.....
.....#GG#WW##WW#GG#.....
.....#GG#KW##WK#GG#.....
.....#gG#WW##WW#gG#.....
.....#GG#KKKKKK#GG#.....
.....#GG#WWRRWw#GG#.....
.....#GGG#KKKK#GGG#.....
.....#gGGGGGGGGgGG#.....
.....#GGGGGGGGGGGG#.....
......#gGGGGGGgGG#......
......#GGgGGGGGGG#......
......#GGGGgGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
........#GGGGGG#........
.........######.........
.........#b##b#.........
"""

# 3. Walk / Run Frame A (Left leg forward, rat limbs kicking)
PICKLE_WALK_A = """
........................
.........######.........
.......##GGLLGG##.......
......#GgGGLLGGGG#......
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGGUUUUUUGGG#.....
.b...#GG#WW##WW#GG#...b.
.Bb..#GG#WK##KW#GG#..bB.
..B..#gG#WW##WW#gG#..B..
...B.#GG#KKKKKK#GG#.B...
....B#GG#WWRRWw#GGB.....
.....#GGG#KKKK#GGG#.....
.....#gGGGGGGGGgGG#.....
.....#GGGGGGGGGGGG#.....
......#gGGGGGGgGG#......
......#GGgGGGGGGG#......
......#GGGGgGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
......B.#GGGGGG#.B......
.....Bb..######...Bb....
....bB.............bB...
....b...............b...
"""

# 4. Walk / Run Frame B (Right leg forward, dynamic stride)
PICKLE_WALK_B = """
........................
........................
.........######.........
.......##GGLLGG##.......
......#GgGGLLGGGG#......
.....#GGGGGGGGGGGG#.....
..b..#gGGgGGGGGGGG#..b..
..Bb.#GGGUUUUUUGGG#.bB..
...B.#GG#WW##WW#GG#.B...
....B#GG#KW##WK#GGB.....
.....#gG#WW##WW#gG#.....
.....#GG#KKKKKK#GG#.....
.....#GG#WWRRWw#GG#.....
.....#GGG#KKKK#GGG#.....
.....#gGGGGGGGGgGG#.....
......#gGGGGGGgGG#......
......#GGgGGGGGGG#......
......#GGGGgGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
........#GGGGGG#........
.....B...######...B.....
....bB.............bB...
....b...............b...
"""

# 5. Climb Frame A (Reaching up with left claw)
PICKLE_CLIMB_A = """
..b.....................
..Bb....................
...B.....######.........
....B..##GGLLGG##.......
.....B#GgGGLLGGGG#......
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGGUUUUUUGGG#.....
.....#GG#WW##WW#GG#.....
.....#GG#WK##KW#GG#..B..
.....#gG#WW##WW#gG#.Bb..
.....#GG#KKKKKK#GG#b....
.....#GG#WWRRWw#GG#.....
.....#GGG#KKKK#GGG#.....
.....#gGGGGGGGGgGG#.....
......#gGGGGGGgGG#......
......#GGgGGGGGGG#......
......#GGGGgGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
........#GGGGGG#.B......
.........######.bB......
.........#b##b#..b......
........................
"""

# 6. Climb Frame B (Reaching up with right claw)
PICKLE_CLIMB_B = """
.....................b..
....................bB..
.........######.....B...
.......##GGLLGG##..B....
......#GgGGLLGGGG#B.....
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGGUUUUUUGGG#.....
.....#GG#WW##WW#GG#.....
..B..#GG#KW##WK#GG#.....
.bB..#gG#WW##WW#gG#.....
..b.#GG#KKKKKK#GG#......
.....#GG#WWRRWw#GG#.....
.....#GGG#KKKK#GGG#.....
.....#gGGGGGGGGgGG#.....
......#gGGGGGGgGG#......
......#GGgGGGGGGG#......
......#GGGGgGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
......B.#GGGGGG#........
......Bb.######.........
......b..#b##b#.........
........................
"""

# 7. Jump Frame (Arms raised in triumph, mouth wide)
PICKLE_JUMP_A = """
...b..................b.
...Bb................bB.
....B....######....B....
.....B.##GGLLGG##.B.....
......#GgGGLLGGGG#......
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGGUUUUUUGGG#.....
.....#GG#WW##WW#GG#.....
.....#GG#WK##KW#GG#.....
.....#gG#WW##WW#gG#.....
.....#GG#KKKKKK#GG#.....
.....#GG#KRRRRK#GG#.....
.....#GGG#KKKK#GGG#.....
.....#gGGGGGGGGgGG#.....
......#gGGGGGGgGG#......
......#GGgGGGGGGG#......
......#GGGGgGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
........#GGGGGG#........
.....B...######...B.....
.....bB..........bB.....
......b..........b......
"""

PICKLE_JUMP_B = PICKLE_JUMP_A  # Fallback

# 8. Fall Frame (Flailing wildly)
PICKLE_FALL_A = """
.b......................
..Bb................bB..
...B.....######.....B...
....B..##GGLLGG##..B....
.....B#GgGGLLGGGG#B.....
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGGUUUUUUGGG#.....
.....#GG#WW##WW#GG#.....
.....#GG#KK##KK#GG#.....
.....#gG#WW##WW#gG#.....
.....#GG#KKKKKK#GG#.....
.....#GG#KRRRRK#GG#.....
.....#GGG#KKKK#GGG#.....
.....#gGGGGGGGGgGG#.....
......#gGGGGGGgGG#......
......#GGgGGGGGGG#......
......#GGGGgGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
......B.#GGGGGG#.B......
.....bB..######...Bb....
.....b.............b....
........................
"""

# 9. Sleep Frame A & B (Passed out, unibrow relaxed, drool)
PICKLE_SLEEP_A = """
........................
........................
.........######.........
.......##GGLLGG##.......
......#GgGGLLGGGG#......
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGguuuuuuGGG#.....
.....#GG#w####w#GG#.....
.....#GG##....##GG#.....
.....#gG#w####w#gG#.....
.....#GG#KKKKKK#GG#.....
.....#GG#WWWWWW#GG#..F..
.....#GGG#KKKK#GGGF.F...
.....#gGGGGGGGGgGGFFF...
......#gGGGGGGgGG#......
......#GGgGGGGGGG#......
......#GGGGgGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
........#GGGGGG#........
.........######.........
.........#b##b#.........
........................
"""

PICKLE_SLEEP_B = """
........................
........................
........................
.........######.........
.......##GGLLGG##.......
......#GgGGLLGGGG#......
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGguuuuuuGGG#.....
.....#GG#w####w#GG#.....
.....#GG##....##GG#.....
.....#gG#w####w#gG#.....
.....#GG#KKKKKK#GG#.....
.....#GG#WWWWWW#GG#...F.
.....#GGG#KKKK#GGGF..F..
.....#gGGGGGGGGgGGFFF...
......#gGGGGGGgGG#......
......#GGgGGGGGGG#......
......#GGGGgGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
........#GGGGGG#........
.........######.........
.........#b##b#.........
"""

# 10. Eat / Serum Frame A & B (Chomping battery / serum flask)
PICKLE_EAT_A = """
........................
.........######.........
.......##GGLLGG##.......
......#GgGGLLGGGG#......
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGGUUUUUUGGG#.....
.....#GG#WW##WW#GG#.....
.....#GG#WK##KW#GG#.....
.....#gG#WW##WW#gG#.....
.....#GG#KKKKKK#GG#.....
..b..#GG#WWWWWW#GG#.....
.bB..#GGG#KRRK#GGG#.....
..B..#gGG#KKKK#gGG#..b..
...BB#GGGG#PP#GGGG#Bb...
....B#gGGG#PP#gGGG#B....
.....#GGgG#PP#GGGG#.....
......#GGG####GGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
........#GGGGGG#........
.........######.........
.........#b##b#.........
........................
"""

PICKLE_EAT_B = """
........................
.........######.........
.......##GGLLGG##.......
......#GgGGLLGGGG#......
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGGUUUUUUGGG#.....
.....#GG#WW##WW#GG#.....
.....#GG#KW##WK#GG#.....
.....#gG#WW##WW#gG#.....
.....#GG#KKKKKK#GG#.....
.....#GG#KKKKKK#GG#..b..
..b..#GGG#KRRK#GGG#Bb...
.bB..#gGGG#KK#gGGG#B....
..BB.#GGGG#PP#GGGG#.....
...B.#gGGG#PP#gGGG#.....
.....#GGgG####GGGG#.....
......#GGGGGGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
........#GGGGGG#........
.........######.........
.........#b##b#.........
........................
"""

# 11. Stunned Frame (Dazed spiral eyes + circling stars)
PICKLE_STUNNED_A = """
....Y................Y..
.....y..............y...
.........######.........
.......##GGLLGG##.......
......#GgGGLLGGGG#......
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGguuuuuuGGG#.....
.....#GG#WK##KW#GG#.....
.....#GG#KW##WK#GG#.....
.....#gG#WW##WW#gG#.....
.....#GG#K####K#GG#.....
.....#GG#KRRRRK#GG#.....
.....#GGG#KKKK#GGG#.....
.....#gGGGGGGGGgGG#.....
......#gGGGGGGgGG#......
......#GGgGGGGGGG#......
......#GGGGgGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
........#GGGGGG#........
.........######.........
.........#b##b#.........
........................
"""

PICKLE_STUNNED_B = """
........Y......Y........
.........y....y.........
.........######.........
.......##GGLLGG##.......
......#GgGGLLGGGG#......
.....#GGGGGGGGGGGG#.....
.....#gGGgGGGGGGGG#.....
.....#GGguuuuuuGGG#.....
.....#GG#KW##WK#GG#.....
.....#GG#WK##KW#GG#.....
.....#gG#WW##WW#gG#.....
.....#GG#K####K#GG#.....
.....#GG#KRRRRK#GG#.....
.....#GGG#KKKK#GGG#.....
.....#gGGGGGGGGgGG#.....
......#gGGGGGGgGG#......
......#GGgGGGGGGG#......
......#GGGGgGGGGG#......
.......#GGGGGGGG#.......
.......#GGgGGGGG#.......
........#GGGGGG#........
.........######.........
.........#b##b#.........
........................
"""

# ==============================================================================
# INCUBATOR / CLONE VAT SPRITES (24 x 24)
# (Replaces the generic egg with Rick's cloning vat with rising bubbles)
# ==============================================================================

INCUBATOR_A = """
........CCCCCCCC........
.......CccccccccC.......
.......C########C.......
.......CFFFFFFFFC.......
.......C#PPPPPP#C.......
.......C#PPPPPP#C.......
.......C#PP..PP#C.......
.......C#PP..PP#C.......
.......C#PPPPPP#C.......
.......C#P.PPPP#C.......
.......C#P.PPPP#C.......
.......C#PPPPPP#C.......
.......C#PPPP.P#C.......
.......C#PPPP.P#C.......
.......C#PPPPPP#C.......
.......C#PPPPPP#C.......
.......CFFFFFFFFC.......
.......C########C.......
......CccccccccccC......
.....CccccccccccccC.....
.....CCCCCCCCCCCCCC.....
.....C############C.....
.....C############C.....
........................
"""

INCUBATOR_B = """
........CCCCCCCC........
.......CccccccccC.......
.......C########C.......
.......CFFFFFFFFC.......
.......C#PPPPPP#C.......
.......C#PP..PP#C.......
.......C#PP..PP#C.......
.......C#PPPPPP#C.......
.......C#PPPPPP#C.......
.......C#PPPPPP#C.......
.......C#P.PPPP#C.......
.......C#P.PPPP#C.......
.......C#PPPPPP#C.......
.......C#PPPPPP#C.......
.......C#PPPP.P#C.......
.......C#PPPP.P#C.......
.......CFFFFFFFFC.......
.......C########C.......
......CccccccccccC......
.....CccccccccccccC.....
.....CCCCCCCCCCCCCC.....
.....C############C.....
.....C############C.....
........................
"""

# ==============================================================================
# GARAGE LAB DECOR SPRITES (24 x 24)
# ==============================================================================

# Portal Gun on workbench
DECOR_PORTAL_GUN = """
........................
........................
........................
........................
........................
........................
........................
........................
...........WW...........
..........WWWW..........
..........WPPW..........
..........WPPW..........
.........WWWWWW.........
........WWWWWWWW........
.......WWWWWWWWWW.......
.......WcSSSSSSsW.......
.......WcSSSSSSsW.......
.......WWWWWWWWWW.......
.........WssssW.........
.........WssssW.........
.........WssssW.........
.........WWWWWW.........
........................
........................
"""

# Bubbling Erlenmeyer Flask
DECOR_FLASK = """
........................
........................
........................
........................
........................
...........CC...........
...........CC...........
...........FF...........
..........FFFF..........
..........FPPF..........
.........FPPPPF.........
.........FPPPPF.........
........FPPPPPPF........
........FPP..PPF........
.......FPPPPPPPPF.......
.......FPPPPPPPPF.......
......FPPPPPPPPPPF......
......FPP..PPPPPPF......
.....FPPPPPPPPPPPPF.....
.....FPPPPPPPPPPPPF.....
.....FFFFFFFFFFFFFF.....
........................
........................
........................
"""

ALL_SPRITES = [
    # Pickle Rick animations
    (PICKLE_IDLE_A, "pickle_idle_a.png"),
    (PICKLE_IDLE_B, "pickle_idle_b.png"),
    (PICKLE_WALK_A, "pickle_walk_a.png"),
    (PICKLE_WALK_B, "pickle_walk_b.png"),
    (PICKLE_CLIMB_A, "pickle_climb_a.png"),
    (PICKLE_CLIMB_B, "pickle_climb_b.png"),
    (PICKLE_JUMP_A, "pickle_jump_a.png"),
    (PICKLE_JUMP_B, "pickle_jump_b.png"),
    (PICKLE_FALL_A, "pickle_fall_a.png"),
    (PICKLE_FALL_A, "pickle_fall_b.png"),
    (PICKLE_SLEEP_A, "pickle_sleep_a.png"),
    (PICKLE_SLEEP_B, "pickle_sleep_b.png"),
    (PICKLE_EAT_A, "pickle_eat_a.png"),
    (PICKLE_EAT_B, "pickle_eat_b.png"),
    (PICKLE_STUNNED_A, "pickle_stunned_a.png"),
    (PICKLE_STUNNED_B, "pickle_stunned_b.png"),

    # Incubator / Clone Vat
    (INCUBATOR_A, "incubator_idle_a.png"),
    (INCUBATOR_B, "incubator_idle_b.png"),

    # Lab Decor
    (DECOR_PORTAL_GUN, "decor_portal_gun.png"),
    (DECOR_FLASK, "decor_flask.png"),
]

def main():
    print("Generating Rick & Morty pixel art assets...")
    for grid, filename in ALL_SPRITES:
        render_grid(grid, filename, 24, 24)
    print("Successfully generated all assets!")

if __name__ == "__main__":
    main()
